import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Bot,Code2,Files,Settings,TerminalSquare,Play,Send,Plus,Trash2,Moon,Sun,RefreshCw,Search,Save,Sparkles,Github,Cloud,Download,Square,ExternalLink,GitCompare,ChevronDown}from'lucide-react';
import'./style.css';

const starter={'README.md':'# BlueAgent Project\n\nBuild something great.\n','index.html':'<!doctype html>\n<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BlueAgent</title></head><body><h1>Hello BlueAgent V2</h1></body></html>\n'};
const T={ar:{chat:'الشات',editor:'المحرر',files:'الملفات',terminal:'الطرفية',settings:'الإعدادات',send:'إرسال',ask:'اطلب من الوكيل إنشاء أو تعديل أو اختبار المشروع…',ready:'جاهز',working:'الوكيل يعمل…',provider:'مزود الذكاء الاصطناعي',url:'رابط API',key:'API Key',model:'النموذج',refresh:'تحديث النماذج',language:'اللغة',theme:'المظهر',newFile:'ملف جديد',save:'حفظ',run:'تشغيل',sandbox:'Sandbox',createSandbox:'تشغيل البيئة',sync:'رفع الملفات للبيئة',pull:'جلب الملفات',preview:'معاينة',stop:'إيقاف',github:'استيراد GitHub',repo:'رابط مستودع GitHub عام',clone:'استيراد',command:'اكتب أمرًا مثل npm install',gitStatus:'Git Status',gitDiff:'Git Diff',clear:'مسح',welcome:'مرحبًا! أنا BlueAgent V2. أقدر أعدل الملفات وأشغّل أوامر واختبارات داخل Vercel Sandbox معزولة. اضبط مزود AI ثم ابدأ.',filter:'بحث/فلترة النماذج',free:'مجاني فقط',company:'الشركة',all:'الكل',add:'إضافة مزود',name:'اسم المزود',providers:'المزودون',security:'مفتاح الـAI محفوظ محليًا في متصفحك. أوامر المشروع تعمل داخل Vercel Sandbox.',empty:'اختر ملفًا لفتحه.',sandboxOff:'Sandbox غير متصل',sandboxOn:'Sandbox متصل',port:'Port',previewCmd:'أمر تشغيل المعاينة',open:'فتح',delete:'حذف'},en:{chat:'Chat',editor:'Editor',files:'Files',terminal:'Terminal',settings:'Settings',send:'Send',ask:'Ask the agent to create, modify, run or test the project…',ready:'Ready',working:'Agent is working…',provider:'AI Provider',url:'API URL',key:'API Key',model:'Model',refresh:'Refresh models',language:'Language',theme:'Theme',newFile:'New file',save:'Save',run:'Run',sandbox:'Sandbox',createSandbox:'Start environment',sync:'Sync files',pull:'Pull files',preview:'Preview',stop:'Stop',github:'Import GitHub',repo:'Public GitHub repository URL',clone:'Import',command:'Type a command, e.g. npm install',gitStatus:'Git Status',gitDiff:'Git Diff',clear:'Clear',welcome:'Hi! I am BlueAgent V2. I can edit files and safely run commands and tests inside an isolated Vercel Sandbox. Configure an AI provider and start building.',filter:'Search/filter models',free:'Free only',company:'Company',all:'All',add:'Add provider',name:'Provider name',providers:'Providers',security:'Your AI key stays in local browser storage. Project commands execute inside Vercel Sandbox.',empty:'Choose a file to open.',sandboxOff:'Sandbox offline',sandboxOn:'Sandbox connected',port:'Port',previewCmd:'Preview start command',open:'Open',delete:'Delete'}};
const uid=()=>Math.random().toString(36).slice(2,9);const load=(k,f)=>{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}};
function App(){
 const[lang,setLang]=useState(()=>load('ba2_lang','ar')),[dark,setDark]=useState(()=>load('ba2_dark',false)),[view,setView]=useState('chat');
 const[files,setFiles]=useState(()=>load('ba2_files',starter)),[selected,setSelected]=useState(()=>Object.keys(load('ba2_files',starter))[0]||''),[draft,setDraft]=useState('');
 const[messages,setMessages]=useState(()=>load('ba2_messages',[{role:'assistant',content:T[load('ba2_lang','ar')].welcome}])),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 const[providers,setProviders]=useState(()=>load('ba2_providers',[{id:uid(),name:'OpenAI compatible',baseUrl:'https://api.openai.com/v1',apiKey:'',models:[],model:''}])),[providerId,setProviderId]=useState(()=>load('ba2_provider',''));
 const[modelSearch,setModelSearch]=useState(''),[company,setCompany]=useState('All'),[freeOnly,setFreeOnly]=useState(false),[np,setNp]=useState({name:'',baseUrl:'',apiKey:''});
 const[sandboxName,setSandboxName]=useState(()=>load('ba2_sandbox','')),[term,setTerm]=useState(()=>load('ba2_terminal','BlueAgent V2 Terminal\n')),[command,setCommand]=useState(''),[repo,setRepo]=useState(''),[previewUrl,setPreviewUrl]=useState(''),[port,setPort]=useState(5173),[previewCmd,setPreviewCmd]=useState('npm run dev -- --host 0.0.0.0 --port 5173');
 const t=T[lang],provider=providers.find(p=>p.id===providerId)||providers[0];
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang;localStorage.setItem('ba2_lang',JSON.stringify(lang))},[lang]);useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('ba2_dark',JSON.stringify(dark))},[dark]);
 useEffect(()=>localStorage.setItem('ba2_files',JSON.stringify(files)),[files]);useEffect(()=>localStorage.setItem('ba2_messages',JSON.stringify(messages)),[messages]);useEffect(()=>localStorage.setItem('ba2_providers',JSON.stringify(providers)),[providers]);useEffect(()=>localStorage.setItem('ba2_provider',JSON.stringify(providerId)),[providerId]);useEffect(()=>localStorage.setItem('ba2_sandbox',JSON.stringify(sandboxName)),[sandboxName]);useEffect(()=>localStorage.setItem('ba2_terminal',JSON.stringify(term)),[term]);useEffect(()=>{if(!providerId&&providers[0])setProviderId(providers[0].id)},[providers,providerId]);useEffect(()=>setDraft(files[selected]??''),[selected,files]);
 const companies=useMemo(()=>['All',...new Set((provider?.models||[]).map(x=>x.company).filter(Boolean))],[provider]);const models=useMemo(()=>(provider?.models||[]).filter(m=>(!modelSearch||`${m.id} ${m.name}`.toLowerCase().includes(modelSearch.toLowerCase()))&&(!freeOnly||m.free)&&(company==='All'||m.company===company)),[provider,modelSearch,freeOnly,company]);
 const patchProvider=x=>setProviders(ps=>ps.map(p=>p.id===provider?.id?{...p,...x}:p));
 async function api(body){const r=await fetch('/api/sandbox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
 async function refreshModels(){try{setStatus(t.refresh);const r=await fetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:provider.baseUrl,apiKey:provider.apiKey})});const d=await r.json();if(!r.ok)throw new Error(d.error);patchProvider({models:d.models,model:provider.model||d.models?.[0]?.id||''});setStatus(`${d.models.length} models`)}catch(e){setStatus(e.message)}}
 async function send(){const q=input.trim();if(!q||busy)return;if(!provider?.baseUrl||!provider?.model){setView('settings');return setStatus(lang==='ar'?'اختر مزودًا ونموذجًا أولًا':'Choose a provider and model first')};const next=[...messages,{role:'user',content:q}];setMessages(next);setInput('');setBusy(true);setStatus(t.working);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:provider.baseUrl,apiKey:provider.apiKey,model:provider.model,messages:next,files,language:lang,sandboxName})});const d=await r.json();if(!r.ok)throw new Error(d.error);setFiles(d.files||files);setSandboxName(d.sandboxName||sandboxName);setMessages(x=>[...x,{role:'assistant',content:d.text,changes:d.changes,trace:d.trace}]);setStatus(t.ready)}catch(e){setMessages(x=>[...x,{role:'assistant',content:`⚠ ${e.message}`}]);setStatus(e.message)}finally{setBusy(false)}}
 function addProvider(){if(!np.baseUrl.trim())return;const p={id:uid(),name:np.name||'Custom provider',baseUrl:np.baseUrl.trim(),apiKey:np.apiKey.trim(),models:[],model:''};setProviders(x=>[...x,p]);setProviderId(p.id);setNp({name:'',baseUrl:'',apiKey:''})}
 function newFile(){const p=prompt(lang==='ar'?'اسم الملف مع المسار':'File path');if(p&&!files[p]){setFiles(x=>({...x,[p]:''}));setSelected(p);setView('editor')}}
 function del(p){const x={...files};delete x[p];setFiles(x);if(selected===p)setSelected(Object.keys(x)[0]||'')}
 async function createSandbox(){try{setStatus(t.createSandbox);const d=await api({action:'create',sandboxName,files});setSandboxName(d.sandboxName);setTerm(x=>x+`\n✓ Sandbox: ${d.sandboxName}\n`);setStatus(t.sandboxOn)}catch(e){setStatus(e.message)}}
 async function sync(){try{const d=await api({action:'sync',sandboxName,files});setSandboxName(d.sandboxName);setTerm(x=>x+`\n✓ Synced ${d.count} files\n`)}catch(e){setTerm(x=>x+`\n✗ ${e.message}\n`)}}
 async function pull(){try{const d=await api({action:'pull',sandboxName});setFiles(d.files||{});setTerm(x=>x+`\n✓ Pulled ${Object.keys(d.files||{}).length} files\n`)}catch(e){setTerm(x=>x+`\n✗ ${e.message}\n`)}}
 async function run(cmd=command){if(!cmd.trim())return;setView('terminal');setTerm(x=>x+`\n$ ${cmd}\n`);setCommand('');try{let name=sandboxName;if(!name){const c=await api({action:'create',files});name=c.sandboxName;setSandboxName(name)}const d=await api({action:'run',sandboxName:name,command:cmd});setSandboxName(d.sandboxName);setTerm(x=>x+(d.stdout||'')+(d.stderr?`\n${d.stderr}`:'')+`\n[exit ${d.exitCode}]\n`)}catch(e){setTerm(x=>x+`✗ ${e.message}\n`)}}
 async function git(kind){try{const d=await api({action:'git',sandboxName,command:kind});setView('terminal');setTerm(x=>x+`\n$ git ${kind}\n${d.stdout||d.stderr||''}\n`)}catch(e){setTerm(x=>x+`\n✗ ${e.message}\n`)}}
 async function clone(){try{let name=sandboxName;if(!name){const c=await api({action:'create',files:{}});name=c.sandboxName;setSandboxName(name)}const d=await api({action:'clone',sandboxName:name,repoUrl:repo});setFiles(d.files);setSelected(Object.keys(d.files)[0]||'');setTerm(x=>x+`\n✓ Imported ${repo}\n`);setView('files')}catch(e){setStatus(e.message)}}
 async function preview(){try{let name=sandboxName;if(!name){const c=await api({action:'create',files});name=c.sandboxName;setSandboxName(name)}else await api({action:'sync',sandboxName:name,files});const d=await api({action:'preview',sandboxName:name,port,command:previewCmd});setPreviewUrl(d.url);window.open(d.url,'_blank','noopener,noreferrer')}catch(e){setStatus(e.message)}}
 async function stop(){try{await api({action:'stop',sandboxName});setSandboxName('');setPreviewUrl('');setStatus(t.sandboxOff)}catch(e){setStatus(e.message)}}
 const nav=[['chat',Bot,t.chat],['editor',Code2,t.editor],['files',Files,t.files],['terminal',TerminalSquare,t.terminal],['settings',Settings,t.settings]];
 return <div className="shell"><aside className="sidebar"><div className="brand"><span><Sparkles size={19}/></span><b>BlueAgent <small>V2</small></b></div><nav>{nav.map(([id,I,l])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}><I size={18}/><em>{l}</em></button>)}</nav><div className="sidefoot"><span className={sandboxName?'dot on':'dot'}/><small>{sandboxName?t.sandboxOn:t.sandboxOff}</small><button onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button></div></aside>
 <main><header><div><b>{nav.find(x=>x[0]===view)?.[2]}</b><span className="sub">{status||`${provider?.name||''}${provider?.model?` · ${provider.model}`:''}`}</span></div><div className="head-actions"><button className="ghost" onClick={sync}><Cloud size={16}/><span>{t.sync}</span></button><button className="primary" onClick={preview}><Play size={16}/><span>{t.preview}</span></button></div></header>
 <section className="content">
 {view==='chat'&&<div className="chat"><div className="messages">{messages.map((m,i)=><div className={`msg ${m.role}`} key={i}><div className="bubble">{m.content}{m.trace?.length>0&&<details><summary>{m.trace.length} tools</summary>{m.trace.map((x,j)=><code key={j}>{x.ok?'✓':'✗'} {x.tool}{x.path?` · ${x.path}`:''}{x.command?` · ${x.command}`:''}</code>)}</details>}{m.changes?.length>0&&<div className="chips">{m.changes.map((x,j)=><span key={j}>{x.type}: {x.path}</span>)}</div>}</div></div>)}</div><div className="composer"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={t.ask} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button disabled={busy} onClick={send}><Send size={18}/></button></div></div>}
 {view==='editor'&&<div className="editor-page"><div className="editorbar"><select value={selected} onChange={e=>setSelected(e.target.value)}>{Object.keys(files).map(p=><option key={p}>{p}</option>)}</select><button onClick={()=>selected&&setFiles(x=>({...x,[selected]:draft}))}><Save size={16}/>{t.save}</button></div>{selected?<textarea className="code" spellCheck="false" value={draft} onChange={e=>setDraft(e.target.value)}/>:<div className="empty">{t.empty}</div>}</div>}
 {view==='files'&&<div className="panel"><div className="panel-title"><h2>{t.files}</h2><button className="primary" onClick={newFile}><Plus size={16}/>{t.newFile}</button></div><div className="filelist">{Object.keys(files).sort().map(p=><div key={p}><button className="filename" onClick={()=>{setSelected(p);setView('editor')}}><Code2 size={15}/>{p}</button><button className="icon danger" onClick={()=>del(p)}><Trash2 size={15}/></button></div>)}</div><div className="import"><h3><Github size={18}/>{t.github}</h3><div className="row"><input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="https://github.com/owner/repo"/><button onClick={clone}>{t.clone}</button></div></div></div>}
 {view==='terminal'&&<div className="terminal-page"><div className="term-actions"><button onClick={createSandbox}><Cloud size={16}/>{t.createSandbox}</button><button onClick={pull}><Download size={16}/>{t.pull}</button><button onClick={()=>git('status')}><Github size={16}/>{t.gitStatus}</button><button onClick={()=>git('diff')}><GitCompare size={16}/>{t.gitDiff}</button><button onClick={stop}><Square size={16}/>{t.stop}</button><button onClick={()=>setTerm('')}>{t.clear}</button></div><pre className="terminal">{term}</pre><div className="term-input"><span>$</span><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder={t.command}/><button onClick={()=>run()}><Play size={16}/>{t.run}</button></div><div className="previewbox"><input type="number" value={port} onChange={e=>setPort(+e.target.value)}/><input value={previewCmd} onChange={e=>setPreviewCmd(e.target.value)} placeholder={t.previewCmd}/><button onClick={preview}><ExternalLink size={16}/>{t.preview}</button>{previewUrl&&<a target="_blank" rel="noreferrer" href={previewUrl}>{t.open}</a>}</div></div>}
 {view==='settings'&&<div className="settings-grid"><div className="card"><h2>{t.provider}</h2><label>{t.providers}<select value={providerId} onChange={e=>setProviderId(e.target.value)}>{providers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>{t.url}<input value={provider?.baseUrl||''} onChange={e=>patchProvider({baseUrl:e.target.value})}/></label><label>{t.key}<input type="password" value={provider?.apiKey||''} onChange={e=>patchProvider({apiKey:e.target.value})}/></label><button onClick={refreshModels}><RefreshCw size={16}/>{t.refresh}</button><label>{t.model}<select value={provider?.model||''} onChange={e=>patchProvider({model:e.target.value})}><option value="">—</option>{models.map(m=><option value={m.id} key={m.id}>{m.name||m.id} · {m.company}{m.free?' · FREE':''}</option>)}</select></label><div className="filters"><div><Search size={15}/><input value={modelSearch} onChange={e=>setModelSearch(e.target.value)} placeholder={t.filter}/></div><select value={company} onChange={e=>setCompany(e.target.value)}>{companies.map(c=><option key={c} value={c}>{c==='All'?t.all:c}</option>)}</select><label className="check"><input type="checkbox" checked={freeOnly} onChange={e=>setFreeOnly(e.target.checked)}/>{t.free}</label></div></div><div className="card"><h2>{t.add}</h2><input value={np.name} onChange={e=>setNp({...np,name:e.target.value})} placeholder={t.name}/><input value={np.baseUrl} onChange={e=>setNp({...np,baseUrl:e.target.value})} placeholder="https://.../v1"/><input type="password" value={np.apiKey} onChange={e=>setNp({...np,apiKey:e.target.value})} placeholder="API Key"/><button onClick={addProvider}><Plus size={16}/>{t.add}</button><hr/><label>{t.language}<select value={lang} onChange={e=>setLang(e.target.value)}><option value="ar">العربية</option><option value="en">English</option></select></label><button onClick={()=>setDark(!dark)}>{dark?<Sun size={16}/>:<Moon size={16}/>} {t.theme}</button><p className="note">{t.security}</p></div></div>}
 </section></main><div className="mobile-nav">{nav.map(([id,I,l])=><button className={view===id?'active':''} onClick={()=>setView(id)} key={id}><I size={19}/><small>{l}</small></button>)}</div></div>
}
createRoot(document.getElementById('root')).render(<App/>);
